### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by kelunik** [gsouf/headless-chromium-php#6]
The package is published as `chrome/chrome` on Packagist. Please use a proper vendor name next time instead of the project name itself.

**Comment by gsouf** [comment]
Hi @kelunik, ``chrome/chrome`` makes sense to me because it's the only viable interface for chrome available on packagist. However if you think it sounds confusing I'm openned for any proposition you can do for the package name.  The project being very young that's still changeable.

**Comment by kelunik** [comment]
It's definitely not the only one. https://github.com/jolicode/asynit/pull/18 will be a separate package in the future and https://packagist.org/packages/jakubkulhan/chrome-devtools-protocol is another one.

**Comment by gsouf** [comment]
Thanks for the links. However next time try to be less rude and I'll try to pay more attention to the vendor name, we are human not robots.
